/**
 * Fabricator — manufactures deliverables from compiled products and Draftsman specifications.
 *
 * Receives:  { compiledProduct, specification, blueprint }
 * Produces:  a deliverable object with a stable id, metadata, payload, and rendered outputs.
 *
 * The deliverable id is derived from compiledProduct.id so it is stable across re-fabrications
 * of the same entity. Downstream callers (Validator, Terminal) rely on this id being present.
 */
'use strict';

function createFabricator({ logger = console } = {}) {

  // ── Input validation ────────────────────────────────────────────────────────
  function validateInput({ compiledProduct, specification, blueprint }) {
    if (!compiledProduct)  throw new Error('Fabricator requires a compiledProduct.');
    if (!specification)    throw new Error('Fabricator requires a Draftsman specification.');
    if (!blueprint)        throw new Error('Fabricator requires a Blueprint definition.');
  }

  // ── Summary derivation ──────────────────────────────────────────────────────
  // Builds a human-readable summary from the compiled product's stats bucket.
  function buildSummary(compiledProduct) {
    const stats = compiledProduct?.stats || {};
    const parts = [];
    if (stats.fans      != null) parts.push(`Fans: ${Number(stats.fans).toLocaleString()}`);
    if (stats.dailyGain != null) parts.push(`Daily: ${stats.dailyGain >= 0 ? '+' : ''}${Number(stats.dailyGain).toLocaleString()}`);
    if (stats.weeklyGain != null) parts.push(`Weekly: ${stats.weeklyGain >= 0 ? '+' : ''}${Number(stats.weeklyGain).toLocaleString()}`);
    if (stats.rankChange != null) parts.push(`Rank Δ: ${stats.rankChange >= 0 ? '+' : ''}${stats.rankChange}`);
    if (stats.flags && stats.flags.length) parts.push(`Flags: ${stats.flags.join(', ')}`);
    return parts.length ? parts.join(' · ') : 'No stats available.';
  }

  // ── Embed renderer ──────────────────────────────────────────────────────────
  function renderEmbed(compiledProduct, specification, blueprint) {
    const stats   = compiledProduct?.stats   || {};
    const profile = compiledProduct?.profile || {};

    const fields = [];
    if (stats.fans      != null) fields.push({ name: 'Fans',         value: String(Number(stats.fans).toLocaleString()),       inline: true });
    if (stats.dailyGain != null) fields.push({ name: 'Daily Gain',   value: `${stats.dailyGain >= 0 ? '+' : ''}${Number(stats.dailyGain).toLocaleString()}`, inline: true });
    if (stats.weeklyGain != null) fields.push({ name: 'Weekly Gain', value: `${stats.weeklyGain >= 0 ? '+' : ''}${Number(stats.weeklyGain).toLocaleString()}`, inline: true });
    if (stats.monthlyGain != null) fields.push({ name: 'Monthly Gain', value: `${stats.monthlyGain >= 0 ? '+' : ''}${Number(stats.monthlyGain).toLocaleString()}`, inline: true });
    if (stats.rankChange != null) fields.push({ name: 'Rank Change', value: `${stats.rankChange >= 0 ? '+' : ''}${stats.rankChange}`, inline: true });
    if (stats.flags && stats.flags.length) fields.push({ name: 'Flags', value: stats.flags.join(', '), inline: false });

    if (!fields.length) {
      fields.push({ name: 'Summary', value: buildSummary(compiledProduct), inline: false });
    }

    return {
      title:       specification?.title || profile.name || compiledProduct?.id || 'Fabricated Deliverable',
      description: specification?.description || 'Generated by UmaKraft.',
      fields,
      footer:      { text: `Blueprint: ${blueprint?.name || 'default'} · id: ${compiledProduct?.id || 'unknown'}` },
      timestamp:   new Date().toISOString(),
    };
  }

  // ── SVG report renderer ─────────────────────────────────────────────────────
  function renderImageReport(compiledProduct, specification, blueprint) {
    const stats   = compiledProduct?.stats   || {};
    const profile = compiledProduct?.profile || {};
    const title   = escapeHtml(specification?.title || profile.name || compiledProduct?.id || 'Fabricated Report');

    const dataLines = [];
    if (stats.fans       != null) dataLines.push(`Fans: ${Number(stats.fans).toLocaleString()}`);
    if (stats.dailyGain  != null) dataLines.push(`Daily gain: ${stats.dailyGain >= 0 ? '+' : ''}${Number(stats.dailyGain).toLocaleString()}`);
    if (stats.weeklyGain != null) dataLines.push(`Weekly gain: ${stats.weeklyGain >= 0 ? '+' : ''}${Number(stats.weeklyGain).toLocaleString()}`);
    if (stats.monthlyGain != null) dataLines.push(`Monthly gain: ${stats.monthlyGain >= 0 ? '+' : ''}${Number(stats.monthlyGain).toLocaleString()}`);
    if (stats.rankChange != null) dataLines.push(`Rank change: ${stats.rankChange >= 0 ? '+' : ''}${stats.rankChange}`);
    if (stats.flags && stats.flags.length) dataLines.push(`Flags: ${stats.flags.join(', ')}`);

    const svgLines = dataLines
      .map((line, i) => `<text x="32" y="${90 + i * 36}" font-family="sans-serif" font-size="20">${escapeHtml(line)}</text>`)
      .join('\n      ');

    const height = Math.max(200, 90 + dataLines.length * 36 + 40);

    return {
      type:    'image-report',
      format:  'svg',
      content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="${height}">
      <text x="32" y="48" font-family="sans-serif" font-size="26" font-weight="bold">${title}</text>
      ${svgLines}
    </svg>`,
      metadata: { blueprint: blueprint?.name || 'default' },
    };
  }

  // ── Main fabricate ──────────────────────────────────────────────────────────
  async function fabricate({ compiledProduct, specification, blueprint }) {
    validateInput({ compiledProduct, specification, blueprint });

    // Stable deliverable id derived from the compiled product.
    // Falls back to specification id or a timestamp-based surrogate.
    const id = compiledProduct?.id
      || specification?.id
      || `deliverable-${Date.now()}`;

    const deliverable = {
      id,
      metadata: {
        source:      specification?.id || 'unknown',
        generatedAt: new Date().toISOString(),
      },
      payload: {
        product:       compiledProduct,
        specification,
        blueprint,
      },
      outputs: {},
    };

    deliverable.outputs.embed       = renderEmbed(compiledProduct, specification, blueprint);
    deliverable.outputs.imageReport = renderImageReport(compiledProduct, specification, blueprint);

    logger.info?.('Fabricator created deliverable', { id }) ??
      console.log('[fabricator]', JSON.stringify({ id, generatedAt: deliverable.metadata.generatedAt }));

    return deliverable;
  }

  // ── Helpers ─────────────────────────────────────────────────────────────────
  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  return { fabricate, renderEmbed, renderImageReport, validateInput };
}

module.exports = createFabricator;
