const path = require('path');
const fs = require('fs').promises;

/**
 * Fabricator is responsible for assembling final deliverables from compiled products,
 * Draftsman specifications, and Blueprint presentation guidance.
 */
function createFabricator({ logger = console } = {}) {
  async function fabricate({ compiledProduct, specification, blueprint }) {
    validateInput({ compiledProduct, specification, blueprint });

    const deliverable = {
      metadata: {
        source: specification?.id || 'unknown',
        generatedAt: new Date().toISOString(),
      },
      payload: {
        product: compiledProduct,
        specification,
        blueprint,
      },
      outputs: {},
    };

    // Placeholder: render outputs using blueprint and compiled product.
    deliverable.outputs.embed = renderEmbed(compiledProduct, specification, blueprint);
    deliverable.outputs.imageReport = renderImageReport(compiledProduct, specification, blueprint);

    logger.info('Fabricator created deliverable', { id: specification?.id });

    return deliverable;
  }

  function renderEmbed(compiledProduct, specification, blueprint) {
    return {
      title: specification?.title || 'Fabricated Deliverable',
      description: specification?.description || 'Generated by the Fabricator.',
      fields: [
        {
          name: 'Product Summary',
          value: compiledProduct?.summary || 'No summary available.',
        },
      ],
      metadata: {
        blueprint: blueprint?.name || 'default',
      },
    };
  }

  function renderImageReport(compiledProduct, specification, blueprint) {
    return {
      type: 'image-report',
      format: 'svg',
      content: `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><text x="32" y="48" font-family="sans-serif" font-size="26">${escapeHtml(
        specification?.title || 'Fabricated Report'
      )}</text></svg>`,
      metadata: {
        blueprint: blueprint?.name || 'default',
      },
    };
  }

  function validateInput({ compiledProduct, specification, blueprint }) {
    if (!compiledProduct) {
      throw new Error('Fabricator requires a compiledProduct.');
    }
    if (!specification) {
      throw new Error('Fabricator requires a Draftsman specification.');
    }
    if (!blueprint) {
      throw new Error('Fabricator requires a Blueprint definition.');
    }
  }

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  return {
    fabricate,
    renderEmbed,
    renderImageReport,
    validateInput,
  };
}

module.exports = createFabricator;
