// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/umakraft-home/Home.tsx": () => import("../components/mockups/umakraft-home/Home.tsx"),
  "./components/mockups/profile-redesign/ProfileRedesign.tsx": () => import("../components/mockups/profile-redesign/ProfileRedesign.tsx")
};
