#!/usr/bin/env node
/**
 * install-hooks.js
 * ────────────────
 * One-time setup: installs the pre-commit git hook that auto-runs generateDocs.js
 * before every commit so all four documentation files are always up to date.
 *
 * Usage:
 *   node scripts/install-hooks.js
 *
 * What it does:
 *   1. Writes .git/hooks/pre-commit
 *   2. Makes it executable (chmod +x)
 *
 * Safe to re-run — overwrites an existing hook with a fresh copy.
 */

import { writeFileSync, chmodSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const hooksDir = path.join(ROOT, '.git', 'hooks');
const hookFile = path.join(hooksDir, 'pre-commit');

if (!existsSync(path.join(ROOT, '.git'))) {
  console.error('❌  Not a git repository — run this from the project root.');
  process.exit(1);
}

mkdirSync(hooksDir, { recursive: true });

const hook = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js — do not edit manually.
# Runs generateDocs.js before every commit so docs stay in sync.

echo "📝 Updating docs…"
node scripts/generateDocs.js
if [ $? -ne 0 ]; then
  echo "❌ generateDocs.js failed — commit aborted."
  exit 1
fi

# Stage any files the script just changed
git add \\
  "UMA_CIRCLE BOT—FULL_REPOSITORY_REPORT.md" \\
  README.md \\
  Projectnotes.md \\
  CHANGELOG.md \\
  2>/dev/null || true

echo "✅ Docs updated and staged."
`;

writeFileSync(hookFile, hook, 'utf8');
chmodSync(hookFile, 0o755);

console.log('✅ pre-commit hook installed →', hookFile);
console.log('   Docs will auto-update before every git commit.');
